server:
  port: 8060
spring:
  application:
    name: hystrix-alex

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9988/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

management:
  endpoint:
    web:
      exposure:
        include: 'hystrix.stream'

